// Generated by Apple Swift version 2.1 (swiftlang-700.1.101.6 clang-700.1.76)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if defined(__has_include) && __has_include(<uchar.h>)
# include <uchar.h>
#elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
#endif

typedef struct _NSZone NSZone;

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted) 
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
#endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#if defined(__has_feature) && __has_feature(modules)
@import UIKit;
@import CoreGraphics;
@import Foundation;
@import CoreData;
@import ObjectiveC;
@import MessageUI;
@import AVFoundation;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class UILabel;
@class NSAttributedString;
@class NSCoder;

SWIFT_CLASS("_TtC8Gulliver23AttributedTableViewCell")
@interface AttributedTableViewCell : UITableViewCell
@property (nonatomic, strong) UILabel * __null_unspecified attributedLabel;
@property (nonatomic, strong) NSAttributedString * __nullable attributedText;
@property (nonatomic) UIEdgeInsets edgeInsets;
- (void)didMoveToSuperview;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class NSBundle;

SWIFT_CLASS("_TtC8Gulliver23ContainerViewController")
@interface ContainerViewController : UIViewController
@property (nonatomic, strong) UIViewController * __nullable currentController;
- (nonnull instancetype)initWithInitialViewController:(UIViewController * __nonnull)initialViewController;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIEvent;

SWIFT_CLASS("_TtC8Gulliver22FullScreenBlockingView")
@interface FullScreenBlockingView : UIView
@property (nonatomic, copy) void (^ __nullable dismissClosure)(void);
+ (FullScreenBlockingView * __nonnull)blockerForViews:(NSArray<UIView *> * __nonnull)targets closure:(void (^ __nullable)(void))closure;
- (UIView * __nullable)hitTest:(CGPoint)point withEvent:(UIEvent * __nullable)event;
- (void)dismiss;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface NSAttributedString (SWIFT_EXTENSION(Gulliver))
- (NSAttributedString * __nonnull)stringByAppendingString:(NSAttributedString * __nonnull)string;
- (NSAttributedString * __nonnull)stringByAppendingString:(NSString * __nonnull)string attributes:(NSDictionary<NSString *, id> * __nonnull)attributes;
@end


@interface NSData (SWIFT_EXTENSION(Gulliver))
@property (nonatomic, readonly, copy) NSString * __nonnull hexString;
- (nullable instancetype)initWithHexString:(NSString * __nonnull)hexString;
@property (nonatomic, readonly, copy) NSString * __nullable string;
@end


@interface NSDate (SWIFT_EXTENSION(Gulliver))
@end


@interface NSDate (SWIFT_EXTENSION(Gulliver))
+ (NSString * __nonnull)ageString:(NSTimeInterval)age style:(NSDateFormatterStyle)style;
@end


@interface NSDate (SWIFT_EXTENSION(Gulliver))
- (NSString * __nonnull)localTimeString:(NSDateFormatterStyle)dateStyle timeStyle:(NSDateFormatterStyle)timeStyle;
@property (nonatomic, readonly) BOOL isToday;
@property (nonatomic, readonly) BOOL isTomorrow;
@property (nonatomic, readonly) BOOL isYesterday;
@property (nonatomic, readonly) NSInteger year;
@property (nonatomic, readonly) NSInteger day;
@property (nonatomic, readonly) NSInteger hour;
@property (nonatomic, readonly) NSInteger minute;
@property (nonatomic, readonly) NSInteger second;
@property (nonatomic, readonly, strong) NSDate * __nonnull nextDay;
@property (nonatomic, readonly, strong) NSDate * __nonnull previousDay;
@property (nonatomic, readonly, strong) NSDate * __nonnull firstSecond;
@property (nonatomic, readonly, strong) NSDate * __nonnull lastSecond;
@property (nonatomic, readonly, strong) NSDate * __nonnull noon;
- (BOOL)isAfter:(NSDate * __nonnull)date;
- (BOOL)isBefore:(NSDate * __nonnull)date;
- (BOOL)isSameDayAs:(NSDate * __nonnull)other;
@end


@interface NSError (SWIFT_EXTENSION(Gulliver))
@property (nonatomic, readonly) BOOL isTimeout;
@property (nonatomic, readonly) BOOL isNoConnection;
@property (nonatomic, readonly, copy) NSArray<NSError *> * __nonnull underlyingErrors;
@end

@class NSURL;

@interface NSFileManager (SWIFT_EXTENSION(Gulliver))
- (BOOL)fileExistsAtURL:(NSURL * __nonnull)url;
- (BOOL)directoryExistsAtURL:(NSURL * __nonnull)url;
@end

@class ThreadsafeToken;

@interface NSManagedObject (SWIFT_EXTENSION(Gulliver))
@property (nonatomic, readonly, strong) ThreadsafeToken * __nonnull token;
@end


@interface NSManagedObject (SWIFT_EXTENSION(Gulliver))
- (void)importDictionary:(NSDictionary<NSString *, id> * __nonnull)dict;
- (void)importRelationship:(NSString * __nonnull)name fromDictionary:(NSDictionary<NSString *, id> * __nonnull)dict;
- (NSManagedObject * __nullable)addRelationship:(NSString * __nonnull)name fromDictionary:(NSDictionary<NSString *, id> * __nonnull)dict;
- (NSString * __nullable)dictionaryKeyToAttributeName:(NSString * __nonnull)key;
- (NSDate * __nullable)dictionaryStringToDate:(NSString * __nonnull)string;
@end

@class NSManagedObjectContext;

@interface NSManagedObject (SWIFT_EXTENSION(Gulliver))
- (id __nullable)objectForKeyedSubscript:(NSString * __nonnull)key;
- (void)setObject:(id __nullable)newValue forKeyedSubscript:(NSString * __nonnull)key;
@property (nonatomic, readonly, strong) NSManagedObjectContext * __nullable moc;
- (NSManagedObject * __nullable)objectInContext:(NSManagedObjectContext * __nonnull)moc;
- (void)log;
+ (NSString * __nonnull)entityName;
- (void)deleteFromContext;
@end


@interface NSManagedObjectContext (SWIFT_EXTENSION(Gulliver))
@end

@class NSFetchRequest;

@interface NSManagedObjectContext (SWIFT_EXTENSION(Gulliver))
- (NSManagedObject * __nonnull)insertEntityNamed:(NSString * __nonnull)name;
- (void)saveAndWait;
- (BOOL)fullySaveAndReturnError:(NSError * __nullable * __null_unspecified)error;
- (void)saveWithCompletion:(void (^ __nullable)(NSError * __nullable))completion;
- (void)saveToDisk;
- (NSFetchRequest * __nonnull)fetchRequest:(NSString * __nonnull)name;
@end


@interface NSMutableAttributedString (SWIFT_EXTENSION(Gulliver))
- (void)addLineBreakOfHeight:(CGFloat)height;
@end


@interface NSMutableAttributedString (SWIFT_EXTENSION(Gulliver))
@end


@interface NSMutableAttributedString (SWIFT_EXTENSION(Gulliver))
- (void)appendString:(NSString * __nonnull)string attributes:(NSDictionary<NSString *, id> * __nonnull)attributes;
- (void)assignAttributes:(NSDictionary<NSString *, id> * __nonnull)attr toUniqueSubstring:(NSString * __nonnull)text;
@end

@class NSDictionary;

@interface NSNotification (SWIFT_EXTENSION(Gulliver))
+ (void)postNotification:(NSString * __nonnull)name object:(id __nullable)object userInfo:(NSDictionary * __nullable)userInfo;
+ (void)postNotificationOnMainThread:(NSString * __nonnull)name object:(id __nullable)object userInfo:(NSDictionary * __nullable)userInfo;
@end


@interface NSObject (SWIFT_EXTENSION(Gulliver))
- (void)addAsObserver:(NSString * __nonnull)name selector:(NSString * __nonnull)selector object:(id __nullable)object;
- (void)removeAsObserver;
@end


@interface NSOperationQueue (SWIFT_EXTENSION(Gulliver))
- (nonnull instancetype)initWithSerial:(BOOL)serial;
- (void)addOperationWithBlockAndWait:(void (^ __nonnull)(void))block;
@end

@class NSMutableParagraphStyle;

@interface NSParagraphStyle (SWIFT_EXTENSION(Gulliver))
+ (NSMutableParagraphStyle * __nonnull)aligned:(NSTextAlignment)alignment;
@end


@interface NSProgress (SWIFT_EXTENSION(Gulliver))
@property (nonatomic) BOOL isDisplayedProgress;
@end


@interface NSUserDefaults (SWIFT_EXTENSION(Gulliver))
+ (void)setCurrentDefaultsGroup:(NSString * __nonnull)group;
+ (NSUserDefaults * __nonnull)defaults;
+ (BOOL)hasValueForKey:(NSString * __nonnull)key;
+ (void)removeValueForKey:(NSString * __nonnull)key;
@end


@interface NSUserDefaults (SWIFT_EXTENSION(Gulliver))
- (BOOL)hasValueForKey:(NSString * __nonnull)key;
- (void)removeValueForKey:(NSString * __nonnull)key;
@end

@protocol NSObject;

SWIFT_CLASS("_TtC8Gulliver8Notifier")
@interface Notifier : NSObject
@property (nonatomic, readonly, copy) NSString * __nonnull name;
- (nonnull instancetype)init:(NSString * __nonnull)nm OBJC_DESIGNATED_INITIALIZER;
- (void)unwatch:(NSObject * __nonnull)observer object:(NSObject * __nullable)object;
- (void)notify:(NSObject * __nullable)object info:(NSDictionary * __nullable)info forceCurrentThread:(BOOL)forceCurrentThread;
- (void)unwatch:(id <NSObject> __nonnull)token;
@end


@interface Notifier (SWIFT_EXTENSION(Gulliver))
@end


SWIFT_PROTOCOL("_TtP8Gulliver19ProgressDisplayable_")
@protocol ProgressDisplayable
@property (nonatomic) double fractionCompleted;
@property (nonatomic) BOOL indeterminate;
- (void)progressDisplayBegan;
- (void)progressDisplayCompleted;
@end

@protocol ProgressDisplayableView;
@class UIButton;
@class UIColor;

SWIFT_CLASS("_TtC8Gulliver15ProgressDisplay")
@interface ProgressDisplay : UIView <ProgressDisplayable>
@property (nonatomic, copy) NSString * __nonnull title;
@property (nonatomic, copy) NSString * __nonnull detailText;
@property (nonatomic, strong) id <ProgressDisplayableView> __nullable determinateView;
@property (nonatomic, strong) id <ProgressDisplayableView> __nullable indeterminateView;
@property (nonatomic, strong) UILabel * __null_unspecified titleLabel;
@property (nonatomic, strong) UILabel * __null_unspecified detailLabel;
@property (nonatomic, strong) UIButton * __nullable button;
@property (nonatomic, strong) UIColor * __nonnull textColor;
@property (nonatomic) BOOL closeWhenComplete;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic) double fractionCompleted;
@property (nonatomic) BOOL indeterminate;
- (ProgressDisplay * __nonnull)close:(BOOL)animated completion:(void (^ __nullable)(void))completion;
- (void)progressDisplayBegan;
- (void)progressDisplayCompleted;
- (ProgressDisplay * __nonnull)show:(BOOL)animated;
- (ProgressDisplay * __nonnull)hide:(BOOL)animated completion:(void (^ __nullable)(void))completion;
- (void)layoutSubviews;
@end



SWIFT_PROTOCOL("_TtP8Gulliver23ProgressDisplayableView_")
@protocol ProgressDisplayableView
@property (nonatomic) double fractionCompleted;
@property (nonatomic, readonly, strong) UIView * __nonnull view;
@property (nonatomic, readonly) BOOL isIndeterminateDisplay;
@end


SWIFT_CLASS("_TtC8Gulliver28SA_MailComposeViewController")
@interface SA_MailComposeViewController : MFMailComposeViewController <MFMailComposeViewControllerDelegate>
@property (nonatomic, copy) void (^ __nullable completion)(MFMailComposeResult);
- (nullable instancetype)initToAddress:(NSString * __nonnull)toAddress subject:(NSString * __nullable)subject body:(NSString * __nullable)body completion:(void (^ __nullable)(MFMailComposeResult))comp;
- (void)mailComposeController:(MFMailComposeViewController * __nonnull)controller didFinishWithResult:(MFMailComposeResult)result error:(NSError * __nullable)error;
- (nonnull instancetype)initWithNavigationBarClass:(Class __nullable)navigationBarClass toolbarClass:(Class __nullable)toolbarClass OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRootViewController:(UIViewController * __nonnull)rootViewController OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8Gulliver16SA_TableViewCell")
@interface SA_TableViewCell : UITableViewCell
@property (nonatomic, strong) UIColor * __nullable dividerColor;
@property (nonatomic, strong) UIView * __nullable dividerView;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8Gulliver11SoundEffect")
@interface SoundEffect : NSObject
+ (BOOL)playSound:(NSString * __nonnull)name;
- (void)play;
- (void)pause;
@property (nonatomic, readonly) BOOL isPlaying;
@end

@class AVAudioPlayer;

SWIFT_CLASS("_TtC8Gulliver11SoundPlayer")
@interface SoundPlayer : NSObject <AVAudioPlayerDelegate>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)audioPlayerDidFinishPlaying:(AVAudioPlayer * __nonnull)player successfully:(BOOL)flag;
@end


@interface UIActivityIndicatorView (SWIFT_EXTENSION(Gulliver)) <ProgressDisplayableView>
@property (nonatomic) double fractionCompleted;
@property (nonatomic, readonly, strong) UIView * __nonnull view;
@property (nonatomic, readonly) BOOL isIndeterminateDisplay;
+ (UIActivityIndicatorView * __nonnull)progressDisplay;
@end


@interface UIAlertController (SWIFT_EXTENSION(Gulliver))
+ (UIAlertController * __nonnull)showAlert:(NSError * __nonnull)error title:(NSString * __nonnull)title;
+ (UIAlertController * __nonnull)showAlert:(NSString * __nonnull)title message:(NSString * __nullable)message buttons:(NSArray<NSString *> * __nonnull)buttons block:(void (^ __nonnull)(NSInteger))block;
+ (void)showNextPendingController;
- (void)present;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (void)cancel:(BOOL)animated completion:(void (^ __nullable)(void))completion;
+ (NSInteger)numberOfPendingAlerts;
@end


@interface UIBezierPath (SWIFT_EXTENSION(Gulliver))
- (void)appendString:(NSAttributedString * __nonnull)string atPoint:(CGPoint)pt withTransform:(CGAffineTransform)withTransform;
@end


@interface UIColor (SWIFT_EXTENSION(Gulliver))
- (nullable instancetype)initWithHex:(NSString * __nonnull)hex;
@property (nonatomic, readonly, copy) NSString * __nonnull hex;
@end


@interface UIDevice (SWIFT_EXTENSION(Gulliver))
@property (nonatomic, readonly) BOOL isIPad;
@end


@interface UIFont (SWIFT_EXTENSION(Gulliver))
- (CGSize)sizeOfString:(NSString * __nonnull)string constrainedToWidth:(CGFloat)width;
@end


@interface UIImage (SWIFT_EXTENSION(Gulliver))
- (UIImage * __nonnull)tintedImage:(UIColor * __nonnull)tint;
- (UIImage * __nonnull)resizedImage:(CGSize)size trimmed:(BOOL)trimmed;
+ (UIImage * __nullable)deviceLaunchImage:(UIDeviceOrientation)orientation;
+ (NSURL * __nullable)deviceLaunchImageURL:(UIDeviceOrientation)orientation;
@end


@interface UIImageView (SWIFT_EXTENSION(Gulliver))
+ (UIImageView * __nullable)deviceLaunchImageView:(UIInterfaceOrientation)orientation;
@end


@interface UILabel (SWIFT_EXTENSION(Gulliver))
@property (nonatomic, readonly, strong) UIFont * __nonnull actualFontInUse;
@end


@interface UIProgressView (SWIFT_EXTENSION(Gulliver)) <ProgressDisplayableView>
@property (nonatomic) double fractionCompleted;
@property (nonatomic, readonly, strong) UIView * __nonnull view;
@property (nonatomic, readonly) BOOL isIndeterminateDisplay;
+ (UIProgressView * __nonnull)progressDisplay;
@end


@interface UIScrollView (SWIFT_EXTENSION(Gulliver))
@property (nonatomic) BOOL resizesForKeyboard;
- (void)gulliver_keyboardWillShow:(NSNotification * __nonnull)note;
- (void)gulliver_keyboardWillHide:(NSNotification * __nonnull)note;
@end


@interface UITextField (SWIFT_EXTENSION(Gulliver))
@end


@interface UIView (SWIFT_EXTENSION(Gulliver))
@property (nonatomic, readonly) CGPoint contentCenter;
- (void)resignFirstResponderForAllSubviews;
- (UIView * __nonnull)blockingViewWithTappedClosure:(void (^ __nullable)(void))closure;
@property (nonatomic, readonly, strong) UIViewController * __nullable viewController;
@property (nonatomic, readonly, strong) UITableViewCell * __nullable tableViewCell;
- (NSString * __nonnull)hierarchy:(NSString * __nullable)prefix;
- (BOOL)isAncestor:(UIView * __nullable)view;
@end


@interface UIView (SWIFT_EXTENSION(Gulliver))
@end


@interface UIViewController (SWIFT_EXTENSION(Gulliver)) <UITextFieldDelegate>
@end

@class UINavigationController;

@interface UIViewController (SWIFT_EXTENSION(Gulliver))
+ (UIViewController * __nonnull)controller;
- (UINavigationController * __nonnull)navigationWrappedController:(BOOL)hideNavigationBar;
+ (UIViewController * __nullable)frontmostController;
- (void)setTabOrder:(NSArray<UIView *> * __nonnull)order withEndOfOrderClosure:(void (^ __nullable)(UIViewController * __nonnull))closure;
@property (nonatomic, readonly, copy) NSArray<UIView *> * __nonnull tabOrder;
- (BOOL)textFieldShouldReturn:(UITextField * __nonnull)textField;
- (BOOL)textField:(UITextField * __nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * __nonnull)string;
@end


@interface UIWindow (SWIFT_EXTENSION(Gulliver))
+ (UIWindow * __nullable)rootWindow;
@end

#pragma clang diagnostic pop
